alter table INSPECTIONRECORD_DEFECT_TYPE_JOB_LINK add constraint FK_DEFTYPJOB_JOB foreign key (JOB_ID) references INSPECTIONRECORD_JOB(ID);
alter table INSPECTIONRECORD_DEFECT_TYPE_JOB_LINK add constraint FK_DEFTYPJOB_DEFECT_TYPE foreign key (DEFECT_TYPE_ID) references INSPECTIONRECORD_DEFECT_TYPE(ID);
